#!/bin/bash
# Install repository guardrails as a pre-commit hook

set -e

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
HOOKS_DIR="$REPO_ROOT/.git/hooks"
PRE_COMMIT_HOOK="$HOOKS_DIR/pre-commit"

# Create hooks directory if it doesn't exist
mkdir -p "$HOOKS_DIR"

# Check if a pre-commit hook already exists
if [ -f "$PRE_COMMIT_HOOK" ] && [ ! -L "$PRE_COMMIT_HOOK" ]; then
    echo "⚠️  A pre-commit hook already exists."
    read -p "Overwrite? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Installation cancelled."
        exit 1
    fi
    # Backup existing hook
    cp "$PRE_COMMIT_HOOK" "$PRE_COMMIT_HOOK.backup.$(date +%Y%m%d%H%M%S)"
    echo "📦 Existing hook backed up."
fi

# Create the pre-commit hook
cat > "$PRE_COMMIT_HOOK" << 'EOF'
#!/bin/bash
# Pre-commit hook for repository guardrails
# This file is auto-generated by install-guardrails.sh

REPO_ROOT="$(git rev-parse --show-toplevel)"
GUARDRAILS_SCRIPT="$REPO_ROOT/scripts/guardrails.py"

if [ -f "$GUARDRAILS_SCRIPT" ]; then
    python3 "$GUARDRAILS_SCRIPT" --staged-only
    exit $?
else
    echo "⚠️  Guardrails script not found: $GUARDRAILS_SCRIPT"
    exit 0  # Don't block commit if script is missing
fi
EOF

chmod +x "$PRE_COMMIT_HOOK"

echo "✅ Guardrails pre-commit hook installed successfully!"
echo "   Location: $PRE_COMMIT_HOOK"
echo ""
echo "The hook will check for:"
echo "   - Files larger than 5MB"
echo "   - Forbidden paths (build/runtime artifacts)"
echo ""
echo "To test the guardrails manually:"
echo "   python3 scripts/guardrails.py"
echo ""
echo "To bypass in exceptional cases:"
echo "   git commit --no-verify"
